#define MAX_PARTICLE_COUNT 16384
#define PARTICLE_RADIUS 2.0f
#define PHYSICS_SUBSTEPS 5
#define EMITTER_RADIUS 16.0f
#define GRAVITIONAL_CONST 98.f
#define AIR_VISCOSITY 1.81e-5
#define TIMESCALE 1.0f